### ISSUE TITLE
Keys not working in Chromium

### ISSUE THREAD

**Issue by iblech** [MatthiasHu/number-theory-shooter#4]
![screenshot](https://user-images.githubusercontent.com/3661115/38989371-f6bf63e6-43d6-11e8-81ed-165820caa531.png)
At the moment, input using keys doesn't seem to work on Chromium.

I tracked the problem down to the `if` statement in `inputMovement`: The branch responsible for handling key input is only executed once, afterwards only the branch for handling motion events is executed. This is because Chromium emits a (spurious?) motion event.

I can confirm that I'm not on a mobile computer. :-)

Attached is a screenshot of the spurious event.

**Comment by MatthiasHu** [comment]
Oh.

Probably the choice between key and accelerometer input should be made in a different way. Maybe the keys WASD should just switch to key input irrevocably (not the other way round).
